remote_theme: pages-themes/slate@v0.2.0

title: All The Monkeys
description: Learn about some monkeys

<details open>
<summary>Want to ruin the surprise?</summary>
<br>
Well, you asked for it!
</details>
