remote_theme: pages-themes/slate@v0.2.0

title: All The Monkeys
description: Learn about some monkeys

- type: dropdown
  name: language
  label: Language
  description: Choose your preferred language.
  options:
  - label: English
    value: en
  - label: Español
    value: es
  - label: 日本語
    value: ja
  - label: Français
    value: fr
